
# Documentation on how this file works can be found here:
# https://zgw-consumers.readthedocs.io/en/latest/setup_config.html


# No default config for the following:
sites_config_enable: false # I dont think we need this
notifications_config_enable: false # Configure notification retry (defaults are ok)
openzaak_selectielijst_config_enable: false # Geen idee of we dit willen beperken?
oidc_db_config_enable: false # This is done in the UI

# Define how to connect to other servies from open-zaak
zgw_consumers_config_enable: True
zgw_consumers:
  services:
    # Default connection to selectielijst (no auth)
    - identifier: selectielijst-api
      label: Selectielijst API
      api_root: https://selectielijst.local/api/v1/
      api_connection_check_path: selectielijst
      api_type: orc
      auth_type: no_auth
    # Reference our notifications API
    - identifier: notifications-api
      label: Notificaties API
      api_root: ${NOTIF_API_ROOT}
      api_connection_check_path: notificaties
      api_type: nrc
      auth_type: zgw
      client_id: ${OPENZAAK_NOTIF_CLIENT_ID}
      secret: ${OPENZAAK_NOTIF_SECRET}
      user_id: ${OPENZAAK_NOTIF_CLIENT_ID}
      user_representation: ${OPENZAAK_NOTIF_CLIENT_ID}


# Defines how others authenticate at this open-zaak
vng_api_common_credentials_config_enable: True
vng_api_common_credentials:
  items:
  - identifier: ${NOTIF_OPENZAAK_CLIENT_ID}
    secret: ${NOTIF_OPENZAAK_SECRET}


# Defines default authorizations (based on client id)
vng_api_common_applicaties_config_enable: True
vng_api_common_applicaties:
  items:
  - uuid: 78591bab-9a00-4887-849c-53b21a67782f # Give permissions to default credential pairs for connections between open-zaak <-> open-notifications
    client_ids:
    - ${NOTIF_OPENZAAK_CLIENT_ID}
    - ${OPENZAAK_NOTIF_CLIENT_ID}
    label: applicatie
    heeft_alle_autorisaties: true


