// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as path from 'path';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

/**
 * Props for NotificationHandlerFunction
 */
export interface NotificationHandlerFunctionProps extends lambda.FunctionOptions {
}

/**
 * An AWS Lambda function which executes src/services/ObjectNotificatieService/NotificationHandler/NotificationHandler.
 */
export class NotificationHandlerFunction extends lambda.Function {
  constructor(scope: Construct, id: string, props?: NotificationHandlerFunctionProps) {
    super(scope, id, {
      description: 'src/services/ObjectNotificatieService/NotificationHandler/NotificationHandler.lambda.ts',
      ...props,
      runtime: new lambda.Runtime('nodejs24.x', lambda.RuntimeFamily.NODEJS),
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '../../../../assets/services/ObjectNotificatieService/NotificationHandler/NotificationHandler.lambda')),
    });
    this.addEnvironment('AWS_NODEJS_CONNECTION_REUSE_ENABLED', '1', { removeInEdge: true });
  }
}