// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as path from 'path';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

/**
 * Props for OperatingHoursEnforcerFunction
 */
export interface OperatingHoursEnforcerFunctionProps extends lambda.FunctionOptions {
}

/**
 * An AWS Lambda function which executes src/constructs/operating-hours/operatingHoursEnforcer.
 */
export class OperatingHoursEnforcerFunction extends lambda.Function {
  constructor(scope: Construct, id: string, props?: OperatingHoursEnforcerFunctionProps) {
    super(scope, id, {
      description: 'src/constructs/operating-hours/operatingHoursEnforcer.lambda.ts',
      ...props,
      runtime: new lambda.Runtime('nodejs24.x', lambda.RuntimeFamily.NODEJS),
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '../../../assets/constructs/operating-hours/operatingHoursEnforcer.lambda')),
    });
    this.addEnvironment('AWS_NODEJS_CONNECTION_REUSE_ENABLED', '1', { removeInEdge: true });
  }
}