// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as path from 'path';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

/**
 * Props for CreateDatabasePerUserFunction
 */
export interface CreateDatabasePerUserFunctionProps extends lambda.FunctionOptions {
}

/**
 * An AWS Lambda function which executes src/custom-resources/create-database-per-user/create-database-per-user.
 */
export class CreateDatabasePerUserFunction extends lambda.Function {
  constructor(scope: Construct, id: string, props?: CreateDatabasePerUserFunctionProps) {
    super(scope, id, {
      description: 'src/custom-resources/create-database-per-user/create-database-per-user.lambda.ts',
      ...props,
      runtime: new lambda.Runtime('nodejs24.x', lambda.RuntimeFamily.NODEJS),
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '../../../assets/custom-resources/create-database-per-user/create-database-per-user.lambda')),
    });
    this.addEnvironment('AWS_NODEJS_CONNECTION_REUSE_ENABLED', '1', { removeInEdge: true });
  }
}