// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as path from 'path';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

/**
 * Props for ArcFunction
 */
export interface ArcFunctionProps extends lambda.FunctionOptions {
}

/**
 * An AWS Lambda function which executes src/services/AttestatieRegistratieComponent/lambda/arc.
 */
export class ArcFunction extends lambda.Function {
  constructor(scope: Construct, id: string, props?: ArcFunctionProps) {
    super(scope, id, {
      description: 'src/services/AttestatieRegistratieComponent/lambda/arc.lambda.ts',
      ...props,
      runtime: new lambda.Runtime('nodejs24.x', lambda.RuntimeFamily.NODEJS),
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '../../../../assets/services/AttestatieRegistratieComponent/lambda/arc.lambda')),
    });
    this.addEnvironment('AWS_NODEJS_CONNECTION_REUSE_ENABLED', '1', { removeInEdge: true });
  }
}