// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as path from 'path';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

/**
 * Props for RegistrationHandlerFunction
 */
export interface RegistrationHandlerFunctionProps extends lambda.FunctionOptions {
}

/**
 * An AWS Lambda function which executes src/services/OpenKlantRegistrationService/RegistrationHandler/registration-handler.
 */
export class RegistrationHandlerFunction extends lambda.Function {
  constructor(scope: Construct, id: string, props?: RegistrationHandlerFunctionProps) {
    super(scope, id, {
      description: 'src/services/OpenKlantRegistrationService/RegistrationHandler/registration-handler.lambda.ts',
      ...props,
      runtime: new lambda.Runtime('nodejs20.x', lambda.RuntimeFamily.NODEJS),
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '../../../../assets/services/OpenKlantRegistrationService/RegistrationHandler/registration-handler.lambda')),
    });
    this.addEnvironment('AWS_NODEJS_CONNECTION_REUSE_ENABLED', '1', { removeInEdge: true });
  }
}